//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionesServicioModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstacionServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstacionServicio()
        {
            this.PuntoCarga = new HashSet<PuntoCarga>();
            this.Horario = new HashSet<Horario>();
        }
    
        public int Id { get; set; }
        public Nullable<int> capacidadMaxima { get; set; }
        public string tarifa { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> direccion { get; set; }
    
        public virtual Direccion Direccion1 { get; set; }
        public virtual Tarifa Tarifa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntoCarga> PuntoCarga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
    }
}
