//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionesServicioModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lectura
    {
        public int Id { get; set; }
        public System.DateTime fecha { get; set; }
        public string valor { get; set; }
        public int tipo { get; set; }
        public string unidadMedida { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Medidor Medidor { get; set; }
    }
}
