//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionesServicioModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedidorConsumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedidorConsumo()
        {
            this.PuntoCarga1 = new HashSet<PuntoCarga>();
        }
    
        public int id { get; set; }
    
        public virtual Medidor Medidor { get; set; }
        public virtual PuntoCarga PuntoCarga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuntoCarga> PuntoCarga1 { get; set; }
    }
}
