//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionesServicioModelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEntities : DbContext
    {
        public BDEntities()
            : base("name=BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<EstacionServicio> EstacionServicio { get; set; }
        public virtual DbSet<Lectura> Lectura { get; set; }
        public virtual DbSet<Medidor> Medidor { get; set; }
        public virtual DbSet<MedidorConsumo> MedidorConsumo { get; set; }
        public virtual DbSet<MedidorTrafico> MedidorTrafico { get; set; }
        public virtual DbSet<PuntoCarga> PuntoCarga { get; set; }
        public virtual DbSet<Tarifa> Tarifa { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
    }
}
