//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionesServicioModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoCarga
    {
        public int id { get; set; }
        public Nullable<int> capacidadMaxima { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public Nullable<int> estacionServicio { get; set; }
        public Nullable<int> medCons { get; set; }
        public Nullable<int> medTraf { get; set; }
        public Nullable<bool> esDual { get; set; }
    
        public virtual EstacionServicio EstacionServicio1 { get; set; }
        public virtual MedidorConsumo MedidorConsumo { get; set; }
        public virtual MedidorTrafico MedidorTrafico { get; set; }
    }
}
